# Generated by Django 4.2.7 on 2025-12-25 21:35

import apps.trabajos.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Carrera')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('color', models.CharField(default='#1e3a8a', max_length=7, verbose_name='Color Hex')),
                ('icono', models.CharField(blank=True, max_length=50, verbose_name='Icono')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Carrera Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('encargados_especial_grado', models.ManyToManyField(blank=True, related_name='carreras_encargado_especial_grado', to=settings.AUTH_USER_MODEL, verbose_name='Encargados Trabajo Especial de Grado')),
                ('encargados_pasantias', models.ManyToManyField(blank=True, related_name='carreras_encargado_pasantias', to=settings.AUTH_USER_MODEL, verbose_name='Encargados Prácticas Profesionales')),
                ('superuser_especial_grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras_superuser_especial_grado', to=settings.AUTH_USER_MODEL, verbose_name='Super Usuario Trabajo Especial de Grado')),
                ('superuser_pasantias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carreras_superuser_pasantias', to=settings.AUTH_USER_MODEL, verbose_name='Super Usuario Prácticas Profesionales')),
            ],
            options={
                'verbose_name': 'Configuración de Carrera',
                'verbose_name_plural': 'Configuraciones de Carreras',
                'db_table': 'configuracion_carrera',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TrabajoInvestigacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('autores', models.CharField(max_length=500, verbose_name='Autores')),
                ('tutores', models.CharField(max_length=500, verbose_name='Tutores')),
                ('tipo_trabajo', models.CharField(choices=[('especial_grado', 'Trabajo Especial de Grado'), ('practicas_profesionales', 'Prácticas Profesionales')], max_length=30, verbose_name='Tipo de Trabajo')),
                ('año', models.PositiveIntegerField(verbose_name='Año')),
                ('archivo_pdf', models.FileField(upload_to=apps.trabajos.models.archivo_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Archivo PDF')),
                ('contenido_extraido', models.TextField(blank=True, verbose_name='Contenido Extraído')),
                ('objetivos', models.TextField(blank=True, verbose_name='Objetivos')),
                ('resumen', models.TextField(blank=True, verbose_name='Resumen')),
                ('tamaño_archivo', models.PositiveIntegerField(verbose_name='Tamaño del Archivo (bytes)')),
                ('hash_md5', models.CharField(blank=True, max_length=32, verbose_name='Hash MD5')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('requiere_correcciones', 'Requiere Correcciones')], default='pendiente', max_length=30, verbose_name='Estado')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('embedding_vector', models.JSONField(blank=True, null=True, verbose_name='Vector de Embedding')),
                ('similitud_trabajo', models.FloatField(default=0.0, verbose_name='Puntuación de Similitud')),
                ('tags_ia', models.JSONField(blank=True, default=list, verbose_name='Tags Generados por IA')),
                ('total_descargas', models.PositiveIntegerField(default=0, verbose_name='Total Descargas')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trabajos.configuracioncarrera', verbose_name='Carrera')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Trabajo de Investigación',
                'verbose_name_plural': 'Trabajos de Investigación',
                'db_table': 'trabajos_investigacion',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='LogActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('upload', 'Subida de archivo'), ('download', 'Descarga de archivo'), ('approve', 'Aprobación'), ('reject', 'Rechazo'), ('delete', 'Eliminación'), ('login', 'Inicio de sesión'), ('search', 'Búsqueda'), ('comment', 'Comentario'), ('rate', 'Calificación')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trabajos.trabajoinvestigacion', verbose_name='Trabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividades',
                'db_table': 'log_actividades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='trabajoinvestigacion',
            index=models.Index(fields=['carrera'], name='trabajos_in_carrera_8cf752_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajoinvestigacion',
            index=models.Index(fields=['tipo_trabajo'], name='trabajos_in_tipo_tr_1cea6b_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajoinvestigacion',
            index=models.Index(fields=['estado'], name='trabajos_in_estado_ed3593_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajoinvestigacion',
            index=models.Index(fields=['año'], name='trabajos_in_año_906843_idx'),
        ),
        migrations.AddIndex(
            model_name='trabajoinvestigacion',
            index=models.Index(fields=['subido_por'], name='trabajos_in_subido__30f392_idx'),
        ),
        migrations.AddIndex(
            model_name='logactividades',
            index=models.Index(fields=['usuario'], name='log_activid_usuario_9998c2_idx'),
        ),
        migrations.AddIndex(
            model_name='logactividades',
            index=models.Index(fields=['accion'], name='log_activid_accion_0bbfb1_idx'),
        ),
        migrations.AddIndex(
            model_name='logactividades',
            index=models.Index(fields=['fecha'], name='log_activid_fecha_f9c570_idx'),
        ),
    ]
