# Generated by Django 4.2.7 on 2025-12-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('encargado_especial_grado', 'Encargado Trabajo Especial de Grado'), ('superuser_especial_grado', 'Super Usuario Trabajo Especial de Grado'), ('encargado_pasantias', 'Encargado Prácticas Profesionales'), ('superuser_pasantias', 'Super Usuario Prácticas Profesionales'), ('administrador', 'Administrador')], default='estudiante', max_length=30, verbose_name='Rol'),
        ),
    ]
